### ISSUE TITLE
Problem with this plugin along with com.admob.google 4.0.7

### ISSUE THREAD

**Issue by tscislo** [danwilson/google-analytics-plugin#126]
When I added
com.admob.google 4.0.7
and
com.danielcwilson.plugins.googleanalytics

to my project after execution of $cordova build I get the following error

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/analytics/internal/Command$1;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)

:dexDebug FAILED

I found out that this is a problem with multiple dependency, but can I solve this in anyway?

Thanks!

**Comment by tscislo** [comment]
Here is stackoverflow post that describes workaroud: http://stackoverflow.com/questions/31451872/cordova-com-danielcwilson-plugins-googleanalytics-with-com-admob-google

**Comment by danwilson** [comment]
It appears this is no longer an issue.
