### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by chrisbenseler** [danwilson/google-analytics-plugin#131]
cordova plugin add cordova-plugin-google-analytics

outputs:

Fetching plugin "cordova-plugin-google-analytics" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-google-analytics
npm http 404 http://registry.cordova.io/cordova-plugin-google-analytics
Error: 404 Not Found: cordova-plugin-google-analytics
at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

Any idea?

**Comment by MingxuanLi** [comment]
+1

**Comment by sidlauskaslukas** [comment]
The problem is that Cordova CLI is trying to fetch plugin with the new "cordova-plugin-*" ID from their registry (CPR) not npm. This happens because you are using 4.x.x version of Cordova CLI. If you want to add plugins with the new "cordova-plugin-*" ID then you have to update your Cordova CLI version to 5.x.x.

**Comment by chrisbenseler** [comment]
Updated to latest cordova (5.1.1) and now it's working. Thanks!

**Comment by danwilson** [comment]
I'll update the README with the distinctions on cordova versions - thanks.
