### ISSUE TITLE
Got "Uh Oh!" Error Message when adding android platform command in ionic

### ISSUE THREAD

**Issue by rebelholic** [danwilson/google-analytics-plugin#135]
Hi,
When I trying add android platform for my ionic project with "Ionic Platform Add Android" Command got error message like below:

>Updated the hooks directory to have execute permissions
Running command: "C:\Program Files\nodejs\node.exe" e:\project\path\hooks\be
fore_platform_add\init_directories.js e:\project\path
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.mycompany.path
        Name: Path App
        Activity: MainActivity
        Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.2
Running command: "C:\Program Files\nodejs\node.exe" e:\project\path\hooks\af
ter_prepare\010_add_platform_class.js e:\project\path
add to body class: platform-android
Running command: "C:\Program Files\nodejs\node.exe" e:\project\path\hooks\af
ter_prepare\020_remove_sass_from_platforms.js e:\project\path
Installing "com.danielcwilson.plugins.googleanalytics" for android
WARNING: com.google.playservices has been renamed to cordova-plugin-googleplayse
rvices. You may not be getting the latest version! We suggest you `cordova plugi
n rm com.google.playservices` and `cordova plugin add cordova-plugin-googleplays
ervices`.
Fetching plugin "com.google.playservices@19.0.0" via cordova plugins registry
Installing "com.google.playservices" for android
Plugin "com.google.playservices" already installed on android.
Installing "com.ionic.keyboard" for android
Installing "cordova-plugin-admobpro" for android
Installing "cordova-plugin-extension" for android
Plugin "cordova-plugin-extension" already installed on android.
Installing "cordova-plugin-google-analytics" for android
WARNING: com.google.playservices has been renamed to cordova-plugin-googleplayse
rvices. You may not be getting the latest version! We suggest you `cordova plugi
n rm com.google.playservices` and `cordova plugin add cordova-plugin-googleplays
ervices`.
Fetching plugin "com.google.playservices@19.0.0" via cordova plugins registry
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-google-analytics':Error: Uh oh!
"e:\project\path\platforms\android\src\com\danielcwilson\plugins\analytics\U
niversalAnalyticsPlugin.java" already exists!
    at Object.module.exports.common.copyNewFile (C:\Users\fake\AppData\Roaming\
npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.j
s:67:19)
    at Object.module.exports.source-file.install (C:\Users\fake\AppData\Roaming
\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android
.js:78:20)
    at installWrapper (C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\n
ode_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\fake\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\plugman\install.js:550:20)
    at C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\install.js:342:28
    at _fulfilled (C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\node_
modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\fake\AppData\Roaming\npm\node_module
s\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\fake\AppData\Roaming\npm\node_
modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.
js:509:49
Error: Uh oh!
"e:\project\path\platforms\android\src\com\danielcwilson\plugins\analytics\U
niversalAnalyticsPlugin.java" already exists!
    at Object.module.exports.common.copyNewFile (C:\Users\fake\AppData\Roaming\
npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.j
s:67:19)
    at Object.module.exports.source-file.install (C:\Users\fake\AppData\Roaming
\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android
.js:78:20)
    at installWrapper (C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\n
ode_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\fake\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\plugman\install.js:550:20)
    at C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\install.js:342:28
    at _fulfilled (C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\node_
modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\fake\AppData\Roaming\npm\node_module
s\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\fake\AppData\Roaming\npm\node_
modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\fake\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.
js:509:49

Although used both "cordova plugin add cordova-plugin-google-analytics" and  "cordova plugin add cordova-plugin-google-analytics@0.7.1" command still not luck before run "Ionic Platform Add Android" Command 

Please fix it!

**Comment by ashishsajwan** [comment]
:+1:  

```
Failed to install 'cordova-plugin-google-analytics':Error: Uh oh!
ENOENT, no such file or directory '/home/entrayn118/websites/entrayn-mobileapp/platforms/android/local.properties'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.createEditor (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
    at Object.module.exports.getProjectSdkDir (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
    at module.exports.framework.install (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
    at Object.ActionStack.process (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!

```

**Comment by rebelholic** [comment]
@ashishsajwan why?

**Comment by ashishsajwan** [comment]
@rebelholic .. updated my comment..
i am also facing similar issue..

**Comment by louisbl** [comment]
This error seems to come from a problem with the Android SDK installation.
Are you able to build a cordova project for Android without any plugins ?
With another cordova plugin it was solved by reinstalling/setting up the android SDK https://github.com/louisbl/cordova-plugin-locationservices/issues/2

**Comment by rebelholic** [comment]
@louisbl when I removed this plugin, I don't get any error messages like above

**Comment by gihant4f** [comment]
I came across this issue due to removing this plugin and then adding again. I've noticed that 2 versions of `com.google.play.srevices` have installed via `phonegap plugin list`. It gave me a hint that when removing plugins, plugin dependencies are not removing. So I manually removed the `com.google.play.srevices` plugins and re add the `com.analytics.google`. 
Problem solved.

**Comment by DreamYahia** [comment]
try to fix this issue by this steps
https://github.com/danwilson/google-analytics-plugin/issues/165#issuecomment-151263435

**Comment by danwilson** [comment]
closing with workaround from @DreamYahia - thanks

**Comment by Medtrack** [comment]
Not working for me any solution.
I don't even have plugin com.analytics.google, I have com.google.playservices.
```
$ cordova prepare android
Error during processing of action! Attempting to revert...
Error: Uh oh!
ENOENT: no such file or directory, scandir '/Users/me/git/myapp/Mobile/Android/loc/platforms/android/com.google.playservices'
```
