### ISSUE TITLE
Install fails with "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by nodesocket** [danwilson/google-analytics-plugin#146]
````
➜  phonegap git:(master) ✗ cordova plugin add https://github.com/danwilson/google-analytics-plugin.git
Fetching plugin "https://github.com/danwilson/google-analytics-plugin.git" via git clone
Repository "https://github.com/danwilson/google-analytics-plugin.git" checked out to git ref "master".
Installing "cordova-plugin-google-analytics" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-google-analytics':TypeError: Uh oh!
Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:424:5)
    at Object.module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at installWrapper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
````

**Comment by custard-apple** [comment]
C:\wamp\www\hello\platforms\android\cordova>build.bat
[TypeError: Path must be a string. Received undefined]



I have the same problem please provide me some solution...

**Comment by danwilson** [comment]
Could you provide more information on this issue? Cordova/PhoneGap CLI versions, Platform versions, etc. Thanks!

**Comment by ottovelazquez** [comment]
I have the same problem
cordova version 4.0.0
platform version android: 3.6.3

**Comment by mavenius** [comment]
I am having the same problem with Cordova 4.2.0 (Ionic 1.7.8).

I noticed that the original poster is using a *nix machine, but the same error happens on Windows.

**Comment by mavenius** [comment]
I just upgraded Cordova to current (5.4.0) and the error is the same:

    Fetching plugin "https://github.com/danwilson/google-analytics-plugin.git" via git clone
    Repository "https://github.com/danwilson/google-analytics-plugin.git" checked out to git ref "master".
    Installing "cordova-plugin-google-analytics" for android
    Error during processing of action! Attempting to revert...
    Failed to install 'cordova-plugin-google-analytics':TypeError: Uh oh!
    Path must be a string. Received undefined
        at assertPath (path.js:8:11)
        at Object.win32.resolve (path.js:130:5)
        at module.exports.framework.install (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android
    .js:139:35)
        at C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:653:27
        at Object.ActionStack.process (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\src\Act
    ionStack.js:56:25)
        at PlatformApiPoly.addPlugin (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:259
    :20)
        at handleInstall (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:603:6)
        at C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:382:28
        at _fulfilled (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
        at self.promiseDispatch.done (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    Error: Uh oh!
    Path must be a string. Received undefined

**Comment by mifaly** [comment]
I have the same problem
cordova version 5.4.0

**Comment by arctouch-andrecardoso** [comment]
Your Android project must have a local.properties file with the `sdk.dir=<absolute path of your local android sdk>` key configured. You can create this file manually or open the project on Android Studio to automatically generate it.

**Comment by jimcamut** [comment]
It could be a permissions issue as it was for me. Try removing the platform and then adding it back, which will reset the permissions.

**Comment by denkomanceski** [comment]
any solution on this ?

**Comment by luisaccedo** [comment]
+1

**Comment by samirfares** [comment]
+1

**Comment by eldyvoon** [comment]
+1

**Comment by Dakuan** [comment]
I also have this, but on removal of local plugins

**Comment by victorsosa** [comment]
This issue is related to the cordova installation, please check that you have the last cordova installed in you machine.

[vns@localhost ~]$ cordova -v
6.2.0

**Comment by wolfbiter** [comment]
in case anyone else runs across this, we were getting this when trying to remove a plugin.

the fix for us was to `nvm use` the correct version of `npm`

**Comment by alouane** [comment]
@victorsosa solution done the job, updating cordova was the key

**Comment by braianj** [comment]
What's the solution for this?
```
$ cordova -v
6.4.0

```

**Comment by brunogyn88** [comment]
`sudo ionic state reset`
`sudo ionic plugin remove cordova-plugin-googlemaps`
