### ISSUE TITLE
0.7.1 not found

### ISSUE THREAD

**Issue by gitarno** [danwilson/google-analytics-plugin#156]
When trying to install the plugin and update libraries to version 0.7.1 was not found, see below:
```
~$ cordova plugin add cordova-plugin-google-analytics@0.7.1
Fetching plugin "cordova-plugin-google-analytics@0.7.1" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-google-analytics/0.7.1
npm http 404 http://registry.cordova.io/cordova-plugin-google-analytics/0.7.1
Error: 404 Not Found: cordova-plugin-google-analytics
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by gitarno** [comment]
I'm closing this issue, and reporting along this [issue 145] (https://github.com/danwilson/google-analytics-plugin/issues/145) it possesses the same error or a similar origin, but which deals with the same subject.

**Comment by gitarno** [comment]
Good morning, my dear friends, I managed to "solve" the need to have a library and be able to do the build in version 0.7.1 through the NPM could see we had two releases, and decided to try in this way, but it is not practical because I had to copy the folder from within node_modules and paste the plugins folder.

From what has to understand is a problem in registry.cordova.io.

```
npm i cordova-plugin-google-analytics@0.7.1
```

**Comment by danwilson** [comment]
I'm unable to reproduce this, can you provide more information such as cordova cli version and cordova platform versions?

**Comment by gitarno** [comment]
The scenario that this error was happening was specific on the date sent, now no longer the case.
I retraced the steps to install the plugin (create, plugin ... @ 0.7.1) and functioned normally.
