### ISSUE TITLE
Conflict with urbanairship-cordova plugin

### ISSUE THREAD

**Issue by piersroberts** [danwilson/google-analytics-plugin#174]
To reproduce, update to the latest currnt version of the Android SDK and cordova build tools;

Use this as your config.xml,

```<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <plugin name="urbanairship-cordova" spec="~3.6.0" />
    <plugin name="cordova-plugin-google-analytics" spec="~0.8.1" />
    <engine name="android" spec="~4.1.1" />
</widget>```

When building I get this error;

```
...
:compileArmv7DebugJava UP-TO-DATE
:preDexArmv7Debug UP-TO-DATE
:dexArmv7Debug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzlv;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

:dexArmv7Debug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexArmv7Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/piersroberts/Development/android-sdk-macosx/build-tools/23.0.0/dx --dex --no-optimize --output /data/doesAndroidWork/platforms/android/build/intermediates/dex/armv7/debug --input-list=/data/doesAndroidWork/platforms/android/build/intermediates/tmp/dex/armv7/debug/inputList.txt
  Error Code:
  	2
  Output:

  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzlv;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by piersroberts** [comment]
Updating `com.google.android.gms:play-services-location` from 8.1.0 to 8.3.0 in urbanairship-cordova fixed this problem
