### ISSUE TITLE
Build Failed due to com.android.dex.DexException:

### ISSUE THREAD

**Issue by chauhan216** [danwilson/google-analytics-plugin#181]
I am using the plugins , cordova-plugin-playservices,  cordova-plugin-google-analytics . When i add the plugn cordova-plugin-google-analytics, the build failed with the error :

	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by JacobSchwartzSoerensen** [comment]
I also have this problem

**Comment by nitzanwilnai** [comment]
Me too. Anyone got this working?

**Comment by aphil** [comment]
Me too, still looking for a solution.

**Comment by betorobson** [comment]
Open Android SDK Manager and update:
Android Support Repository
Android Support Library
Google Play Services
Google Repository

Do not forget to restart Android SDK Manager and repeat update process until there is no more updates.

**Comment by Colin-R** [comment]
I'm having the same issue.

Updating Android SDK tools did not fix this for me.

**Comment by betorobson** [comment]
Remove it by this command:
`cordova plugin remove cordova-plugin-google-analytics`

And install again this command:
`cordova plugin add com.danielcwilson.plugins.googleanalytics`

**Comment by Colin-R** [comment]
The above fixed this problem for me.

Thanks betorobson!

**Comment by fryck** [comment]
i'm still looking for a solution...

Fetching plugin "com.danielcwilson.plugins.googleanalytics" via npm
Error: Failed to fetch plugin com.danielcwilson.plugins.googleanalytics via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.danielcwilson.plugins.googleanalytics

Build failed.

**Comment by victorsosa** [comment]
@betorobson thanks
