### ISSUE TITLE
Issue trying to install plugin

### ISSUE THREAD

**Issue by victorsosa** [danwilson/google-analytics-plugin#231]
HI,

Trying to install, here is the message I got:

```
[vns@localhost outing2]$ cordova plugin add cordova-plugin-google-analytics
Fetching plugin "cordova-plugin-google-analytics" via plugin registry
Error: connect ETIMEDOUT 50.17.177.14:80
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
```

Thanks

**Comment by victorsosa** [comment]
Fixed, I was trying to install the plugin using the cordova version 4.2.0
