### ISSUE TITLE
Uncaught Exception, TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by barocsi** [danwilson/google-analytics-plugin#351]
I have no idea how to debug it.

1.6.0, 1.7.x
```
main.js:70913 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at get (file:///android_asset/www/build/main.js:129829:32)
    at getPlugin (file:///android_asset/www/build/main.js:394:85)
    at callCordovaPlugin (file:///android_asset/www/build/main.js:481:26)
    at file:///android_asset/www/build/main.js:530:24
    at file:///android_asset/www/build/main.js:502:17
    at new t (file:///android_asset/www/build/polyfills.js:3:11329)
    at tryNativePromise (file:///android_asset/www/build/main.js:501:20)
    at getPromise (file:///android_asset/www/build/main.js:523:16)
    at wrapPromise (file:///android_asset/www/build/main.js:529:13)
    at AnalyticsService.<anonymous> (file:///android_asset/www/build/main.js:696:20)
```

**Comment by victorsosa** [comment]
Sorry this is you code, won't fix
```
TypeError: Cannot read property 'split' of undefined
    at get (file:///android_asset/www/build/main.js:129829:32)
```
