### ISSUE TITLE
Error building for iOS

### ISSUE THREAD

**Issue by gudeidea** [danwilson/google-analytics-plugin#501]
My project works fine in Android, but when I try to build my app to iOS, I'm getting this error:

<pre>
Dependent plugin "cordova-plugin-dialogs" already installed on ios.

Dependent plugin "cordova-plugin-globalization" already installed on ios.
Installing "cordova-plugin-google-analytics" for ios
Error during processing of action! Attempting to revert...

Failed to install 'cordova-plugin-google-analytics': CordovaError: Uh oh!
"/Users/user/Documents/APP/plugins/cordova-plugin-google-analytics/ios/libGoogleAnalyticsServices.a" not found!
    at copyFile (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
    at copyNewFile (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
    at installHelper (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/user/Documents/APP/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/user/Documents/APP/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/user/Documents/APP/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/user/Documents/APP/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/Users/user/Documents/APP/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/user/Documents/APP/node_modules/cordova-lib/src/plugman/install.js:357:28

(node:889) UnhandledPromiseRejectionWarning: CordovaError: Uh oh!
"/Users/user/Documents/APP/plugins/cordova-plugin-google-analytics/ios/libGoogleAnalyticsServices.a" not found!
    at copyFile (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
    at copyNewFile (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
    at installHelper (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/Users/user/Documents/APP/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/user/Documents/APP/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/user/Documents/APP/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/user/Documents/APP/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/user/Documents/APP/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/Users/user/Documents/APP/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/user/Documents/APP/node_modules/cordova-lib/src/plugman/install.js:357:28
(node:889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

**Comment by victorsosa** [comment]
it said not found but the file is in place in the repo:

"/Users/user/Documents/APP/plugins/cordova-plugin-google-analytics/ios/libGoogleAnalyticsServices.a" not found!

try remove and reinstall the plugin

**Comment by victorsosa** [comment]
PR https://github.com/danwilson/google-analytics-plugin/pull/594 created
