### ISSUE TITLE
startTrackerWithId not working

### ISSUE THREAD

**Issue by afurusawa** [danwilson/google-analytics-plugin#529]
Here's my ionic info:
```
cli packages: (/Users/andrewfurusawa/.nvm/versions/node/v9.6.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 7.0.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v9.6.1
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : /Users/andrewfurusawa/Library/Android/sdk

Misc:

    backend : pro
```

and here's the error log I'm getting:

```07-31 23:12:29.546 26829 26901 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbo;
07-31 23:12:29.546 26829 26901 W System.err: 	at com.google.android.gms.internal.zzami.zzaf(Unknown Source:0)
07-31 23:12:29.546 26829 26901 W System.err: 	at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source:0)
07-31 23:12:29.546 26829 26901 W System.err: 	at com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin.startTracker(UniversalAnalyticsPlugin.java:145)
07-31 23:12:29.546 26829 26901 W System.err: 	at com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin.execute(UniversalAnalyticsPlugin.java:53)
07-31 23:12:29.546 26829 26901 W System.err: 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
07-31 23:12:29.547 26829 26901 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
07-31 23:12:29.547 26829 26901 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
07-31 23:12:29.547 26829 26901 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-31 23:12:29.547 26829 26901 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
07-31 23:12:29.547 26829 26901 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SourceFile:9)
07-31 23:12:29.547 26829 26901 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-31 23:12:29.547 26829 26901 W System.err: 	at android.os.Looper.loop(Looper.java:164)
07-31 23:12:29.547 26829 26901 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
07-31 23:12:29.548 26829 26901 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbo" on path: DexPathList[[zip file "/data/app/com.scotts.groconnect-VhjOflE47_1y5Jai2-H2yw==/base.apk"],nativeLibraryDirectories=[/data/app/com.scotts.groconnect-VhjOflE47_1y5Jai2-H2yw==/lib/arm64, /system/lib64, /vendor/lib64]]
07-31 23:12:29.548 26829 26901 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
07-31 23:12:29.548 26829 26901 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-31 23:12:29.548 26829 26901 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-31 23:12:29.548 26829 26901 W System.err: 	... 13 more
```

Context:
I looked around for possible solutions and some people mentioned enabling multidex, which I did and it still doesn't work.

**Comment by victorsosa** [comment]
do this:

1. remove android platform 
2. add android platform

that should fix you issue.

**Comment by yosigolan** [comment]
i see the same thing in version 1.8.6. version 1.8.3 works fine.

**Comment by spinninghamster** [comment]
I can confirm I have the same issue.

`window.analytics.startTrackerWithId('XXXXX');` is never being called. Which one is the last version working for you?

**Comment by vignitres** [comment]
Did you find a solution for this?

**Comment by spinninghamster** [comment]
`window.analytics.startTrackerWithId('UA-XXXXXXXX-X');`

is working if you call it right after `deviceready`.

**Comment by victorsosa** [comment]
issue #551 related to this one
