### ISSUE TITLE
Problems on included libraries with 1.8.6 and java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by mathatan** [danwilson/google-analytics-plugin#534]
We're experiencing a strange issue with 1.8.6 where the builds work perfectly fine and even install from apk to device performs as expected, but when installing from Google Play Store app crashes on first run to `java.lang.NoClassDefFoundError`. 

We've identified that downgrading google-analytics-plugin to 1.8.3 fixes the issue. Setting `GMS_VERSION` variable has in config.xml for 1.8.6 has no effect. This issue persist on multiple android platforms and there seems to be no connecting factor besides the plugin and install from Play Store.

The Google Play Store error throw log is:
```
java.lang.NoClassDefFoundError: 
  at com.google.android.gms.internal.zzami.zzaf (Unknown Source)
  at com.google.android.gms.analytics.CampaignTrackingReceiver.onReceive (Unknown Source)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3390)
  at android.app.ActivityThread.-wrap18 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:93)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
```

Android studio is using the currently available libraries with the exception of NDK version which is 16b (this is to enable building of Android platform 6.4.0)

OS: MacOS High Sierra 10.13.6
Cordova version 8.0.0
Android platform version 6.4.0
Plugins:
```
branch-cordova-sdk 3.0.0 "branch-cordova-sdk"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-appsflyer-sdk 4.2.23 "AppsFlyer"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-multidex 0.1.2 "Cordova Multi Dex"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
pushwoosh-cordova-plugin 7.8.7 "Pushwoosh"
```

With the addition of
```
cordova-plugin-google-analytics 1.8.x "Google Universal Analytics Plugin"
```

1.8.3 works perfectly fine but 1.8.6 crashes. But only if installed from Google Play Store and even then only on initial run. (I'm not entirely sure about only crashing on initial run, it might crash on any)

Due to issue appearing only on Google Play Store installs getting more detailed error reports is somewhat difficult and we've been unable to reproduce the issue with local installs.

**Comment by gabiriel** [comment]
Thanks for your help concerning the working version 1.8.3, I faced the same issue yesterday when I pushed on the PlayStore (I haven't test on Apple Store)
Here are my plugins:

> cordova-admob-sdk 0.17.0 "AdMob SDK"
cordova-plugin-admob-free 0.15.0 "Cordova AdMob Plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
es6-promise-plugin 4.2.2 "Promise"

with
> cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"

**Comment by alfredteo36** [comment]
i face the same issue too. Tracking is not working in google analytics for android

**Comment by alfredteo36** [comment]
08-24 13:55:19.391 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/common/util/zze;)
    VFY: unable to find class referenced in signature (Lcom/google/android/gms/common/util/zze;)
08-24 13:55:19.392 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzcF, referenced from method com.google.android.gms.analytics.zza.zzaY
08-24 13:55:19.392 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30239: Lcom/google/android/gms/common/internal/zzbo;.zzcF (Ljava/lang/String;)Ljava/lang/String;
08-24 13:55:19.392 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0000
08-24 13:55:19.394 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/common/util/zze;)
08-24 13:55:19.394 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzu, referenced from method com.google.android.gms.analytics.zzk.<init>
08-24 13:55:19.394 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30243: Lcom/google/android/gms/common/internal/zzbo;.zzu (Ljava/lang/Object;)Ljava/lang/Object;
08-24 13:55:19.394 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0003
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzb, referenced from method com.google.android.gms.internal.zzami.<init>
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30237: Lcom/google/android/gms/common/internal/zzbo;.zzb (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0009
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzb, referenced from method com.google.android.gms.internal.zzami.zza
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30237: Lcom/google/android/gms/common/internal/zzbo;.zzb (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzu, referenced from method com.google.android.gms.internal.zzami.zzaf
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30243: Lcom/google/android/gms/common/internal/zzbo;.zzu (Ljava/lang/Object;)Ljava/lang/Object;
08-24 13:55:19.395 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0000
08-24 13:55:19.396 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzu, referenced from method com.google.android.gms.internal.zzami.zzkG
08-24 13:55:19.396 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30243: Lcom/google/android/gms/common/internal/zzbo;.zzu (Ljava/lang/Object;)Ljava/lang/Object;
08-24 13:55:19.396 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
08-24 13:55:19.397 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/common/util/zze;)
08-24 13:55:19.398 3978-4051/com.pricesmartly.v1 I/dalvikvm: Could not find method com.google.android.gms.common.internal.zzbo.zzu, referenced from method com.google.android.gms.internal.zzami.zzkt
08-24 13:55:19.398 3978-4051/com.pricesmartly.v1 W/dalvikvm: VFY: unable to resolve static method 30243: Lcom/google/android/gms/common/internal/zzbo;.zzu (Ljava/lang/Object;)Ljava/lang/Object;
08-24 13:55:19.398 3978-4051/com.pricesmartly.v1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
08-24 13:55:19.399 3978-4051/com.pricesmartly.v1 W/System.err: java.lang.NoClassDefFoundError: com.google.android.gms.common.internal.zzbo
        at com.google.android.gms.internal.zzami.zzaf(Unknown Source)
08-24 13:55:19.400 3978-4051/com.pricesmartly.v1 W/System.err:     at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
        at com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin.startTracker(UniversalAnalyticsPlugin.java:145)
        at com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin.execute(UniversalAnalyticsPlugin.java:53)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)

**Comment by victorsosa** [comment]
GMS_VERSION is a OS variable, it need to be added to the env

**Comment by alexlopezit** [comment]
Same issue here, downgrading to 1.8.2 work for me

**Comment by malwatte** [comment]
I had this issue in 1.8.6 and I changed the gms version to 16.0.3 and it started to work.

`cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3`

Check other plugins and change the GMS_VERSION version accordingly

**Comment by victorsosa** [comment]
related to #551
